#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Game1")]
	public partial class ScoresDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ScoresDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		/*public ScoresDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}*/
		
		public ScoresDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		/*public ScoresDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}*/
		
		public System.Data.Linq.Table<Score> Scores
		{
			get
			{
				return this.GetTable<Score>();
			}
		}
	}

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "Scores")]
    public partial class Score : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Score1;

        private System.DateTime _When;

        private int _Id;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnScore1Changing(int value);
        partial void OnScore1Changed();
        partial void OnWhenChanging(System.DateTime value);
        partial void OnWhenChanged();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        #endregion

        public Score()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "score", Storage = "_Score1", DbType = "Int NOT NULL")]
        public int Score1
        {
            get
            {
                return this._Score1;
            }
            set
            {
                if ((this._Score1 != value))
                {
                    this.OnScore1Changing(value);
                    this.SendPropertyChanging();
                    this._Score1 = value;
                    this.SendPropertyChanged("Score1");
                    this.OnScore1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "when", Storage = "_When", DbType = "DateTime NOT NULL")]
        public System.DateTime When
        {
            get
            {
                return this._When;
            }
            set
            {
                if ((this._When != value))
                {
                    this.OnWhenChanging(value);
                    this.SendPropertyChanging();
                    this._When = value;
                    this.SendPropertyChanged("When");
                    this.OnWhenChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "id", Storage = "_Id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
